### ISSUE TITLE
Tree construction

### ISSUE THREAD

**Issue by AldawsariNLP** [NLPbox/codra-docker#3]
Hello, 
Is there any documentation for the tree construction (the output), so that it can be reconstructed ? e.g. reconstructing the tree using networkx library in python.

**Comment by arne-cl** [comment]
Hi @AldawsariNLP,

there's no documentation beyond the code itself and the Joty et al. (2015) paper.

You can use my [rst-converter-service](https://github.com/arne-cl/rst-converter-service) to convert the tree into other formats. Under the hood, it uses the [discoursegraphs](https://github.com/arne-cl/discoursegraphs) library ([Neumann 2015](http://www.aclweb.org/anthology/W15-1843)) that parses/produces a number of linguistic file formats.

Here's the [entrypoint](https://github.com/arne-cl/discoursegraphs/blob/master/src/discoursegraphs/readwrite/rst/dis/codra.py) in the codebase for parsing CODRA's output format into `nltk.Trees`.
There's also a [module to parse .dis files into networkx graphs](https://github.com/arne-cl/discoursegraphs/blob/master/src/discoursegraphs/readwrite/rst/dis/disgraph.py). 
Since CODRA's format is basically the .dis format, you'd just need to add some preprocessing
(like [this](https://github.com/arne-cl/discoursegraphs/blob/master/src/discoursegraphs/readwrite/rst/dis/codra.py)).

**Comment by AldawsariNLP** [comment]
Thanks you. I think the module to parse .dis files into networkx graphs is what I want. However, I build an image using Docker and run the module but got an error:
 NotImplementedError: I don't know how to combine two satellites

Do you have an idea to go around this error?  I am newbie to all these formats 

my work: 
I have a folder contains about 100 docs in .dis format which is the output of CODRA parser and I need to convert these files to any format (graph) that can be easy to query when we need to find out the discourse relation between two EDUs.  Any idea? 

Thank you

**Comment by arne-cl** [comment]
Dear @AldawsariNLP ,
can you send me one of the files that causes the `NotImplementedError`?
I guess I didn't implement it because I didn't have a .dis parse that contained two satellites.

**Comment by AldawsariNLP** [comment]
I attached the file. 

[doc1.txt](https://github.com/NLPbox/codra-docker/files/2672525/doc1.txt)

**Comment by AldawsariNLP** [comment]
I was able to convert the .dis files to rs3 then used rs3graph.py to convertthe  files into a networkx-based directed graph. But the question is how to write the networkx-based directed graph to files  then load them using networkx 
I did not understand this command: 
generic_converter_cli(RSTGraph, 'RST (rhetorical structure)')

**Comment by arne-cl** [comment]
Dear @AldawsariNLP,

once you have converted the rs3 file into a graph

```python
>>> import networkx as nx
>>> import discoursegraphs as dg

>>> dt = dg.read_distree('/tmp/doc1.txt')
>>> dg.write_rs3(dt, '/tmp/doc1.rs3')

>>> rst_graph = dg.read_rs3('/tmp/doc1.rs3')
```

you have already reached your goal. `rst_graph` is an `RSTGraph`,
which is basically a subclass of a networkx MultiDiGraph:

```python
>>> import inspect
>>> inspect.getmro(type(rst_graph))

(discoursegraphs.readwrite.rst.rs3.rs3graph.RSTGraph,
 discoursegraphs.discoursegraph.DiscourseDocumentGraph,
 networkx.classes.multidigraph.MultiDiGraph,
 networkx.classes.multigraph.MultiGraph,
 networkx.classes.digraph.DiGraph,
 networkx.classes.graph.Graph,
 object)
```

networkx supports a number of importers and exporters (`nx.write_*` and `nx.read_*`).
I've found their exporters insufficient for the graphs that I produce, so I wrote custom
exporters in the `discoursegraphs` library for formats that `networkx` can import.

For example, this works:

```python
>>> dg.write_gexf(rst_graph, '/tmp/doc1.gexf')
>>> nx_rst_graph = nx.read_gexf('/tmp/doc1.gexf')
>>> type(nx_rst_graph)
networkx.classes.digraph.DiGraph
```

I hope this helps. If you use this for research, please cite my [discoursegraphs paper](http://www.aclweb.org/anthology/W15-1843).

**Comment by AldawsariNLP** [comment]
Thank you, worked. Of course, it will be cited.
